In [1]:
# So here I am starting with ground zero, to get myself calibrate with the field of Data Science. 
# Python is the best and most used programming language to work with data.
# Step 1: Learn Basics of Python: Data Structures (This is from DataCamp Tutorial Practice)
# Data structures are a way of organizing and storing data so that they can be accessed and worked with efficiently. 
# They define the relationship between the data, and the operations that can be performed on the data. 
# There are many various kinds of data structures defined that make it easier for the data scientists and the computer engineers, 
# alike to concentrate on the main picture of solving larger problems rather than getting lost in the details of data description
# and access.

x='apple'
y=str.capitalize(x)
print(x + y)

appleApple


In [2]:
print(x + '\n' + y)

apple
Apple


In [3]:
print(x,y)

apple Apple


In [14]:
print("capitalization of %s is %s" %(x, y))

capitalization of apple is Apple


In [15]:
import array as arr
a = arr.array("I",[3,6,9])
type(a)

array.array

In [16]:
list_num = [1,2,45,6,7,2,90,23,435]
list_char = ['c','o','o','k','i','e']

list_num.append(11) # Add 11 to the list, by default adds to the last position
print(list_num)

[1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [17]:
list_num.insert(0, 11)
print(list_num)

[11, 1, 2, 45, 6, 7, 2, 90, 23, 435, 11]


In [18]:
list_char.remove('o') 
print(list_char)

['c', 'o', 'k', 'i', 'e']


In [19]:
list_char.pop(-2) # Removes the item at the specified position
print(list_char)

['c', 'o', 'k', 'e']


In [20]:
list_num.sort() # In-place sorting
print(list_num)

[1, 2, 2, 6, 7, 11, 11, 23, 45, 90, 435]


In [21]:
list.reverse(list_num)
print(list_num)

[435, 90, 45, 23, 11, 11, 7, 6, 2, 2, 1]


In [22]:
print(list_num[3])

23


In [24]:
#Array vs. Lists

array_char = arr.array("u",["c","a","t","s"])
array_char.tostring()
print(array_char)

array('u', 'cats')


In [25]:
import numpy as np

arr_a = np.array([3, 6, 9])
arr_b = arr_a/3 # Performing vectorized (element-wise) operations 
print(arr_b)

[ 1.  2.  3.]


In [26]:
arr_ones = np.ones(4)
print(arr_ones)

[ 1.  1.  1.  1.]


In [27]:
multi_arr_ones = np.ones((3,4)) # Creating 2D array with 3 rows and 4 columns
print(multi_arr_ones)

[[ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]
 [ 1.  1.  1.  1.]]


In [28]:
stack = [1,2,3,4,5] 
stack.append(6) # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 -> 6 (Top)
print(stack)

[1, 2, 3, 4, 5, 6]


In [29]:
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 -> 5 (Top)
stack.pop() # Bottom -> 1 -> 2 -> 3 -> 4 (Top)
print(stack)

[1, 2, 3, 4]


In [30]:
graph = { "a" : ["c", "d"],
          "b" : ["d", "e"],
          "c" : ["a", "e"],
          "d" : ["a", "b"],
          "e" : ["b", "c"]
        }


In [31]:
def define_edges(graph):
    edges = []
    for vertices in graph:
        for neighbour in graph[vertices]:
            edges.append((vertices, neighbour))
    return edges

In [32]:
print(define_edges(graph))

[('a', 'c'), ('a', 'd'), ('b', 'd'), ('b', 'e'), ('c', 'a'), ('c', 'e'), ('d', 'a'), ('d', 'b'), ('e', 'b'), ('e', 'c')]


In [33]:
class Tree:
    def __init__(self, info, left=None, right=None):
        self.info = info
        self.left  = left
        self.right = right

    def __str__(self):
        return (str(self.info) + ', Left child: ' + str(self.left) + ', Right child: ' + str(self.right))

tree = Tree(1, Tree(2, 2.1, 2.2), Tree(3, 3.1))
print(tree)

1, Left child: 2, Left child: 2.1, Right child: 2.2, Right child: 3, Left child: 3.1, Right child: None


In [34]:
x_tuple = 1,2,3,4,5
y_tuple = ('c','a','k','e')
x_tuple[0]

1

In [35]:
x_tuple[0] = 0 # Cannot change values inside a tuple

TypeError: 'tuple' object does not support item assignment

In [36]:
x_dict = {'Edward':1, 'Jorge':2, 'Prem':3, 'Joe':4}
del x_dict['Joe']
x_dict

{'Edward': 1, 'Jorge': 2, 'Prem': 3}

In [37]:
x_dict['Edward']

1

In [38]:
len(x_dict)

3

In [42]:
x_dict.keys()

dict_keys(['Edward', 'Jorge', 'Prem'])

In [41]:
x_dict.values()

dict_values([1, 2, 3])

In [43]:
x_set = set('CAKE&COKE')
y_set = set('COOKIE')

print(x_set)

{'A', '&', 'C', 'O', 'E', 'K'}


In [45]:
print(y_set)

{'C', 'O', 'E', 'K', 'I'}


In [46]:
print(x-y)

TypeError: unsupported operand type(s) for -: 'str' and 'str'

In [47]:
print(x_set|y_set)

{'A', '&', 'C', 'O', 'E', 'K', 'I'}


In [48]:
print(x_set & y_set)

{'K', 'E', 'O', 'C'}


In [49]:
f=open('ronak','w')

In [50]:
f.read()

UnsupportedOperation: not readable

In [51]:
f=open('ronak.txt','w')
f.read()

UnsupportedOperation: not readable

In [52]:
f.close()